### ISSUE TITLE
I want to know more about your addons :)

### ISSUE THREAD

**Issue by Macumbafeh** [Spikeone/WoWAddons#5]
Hey ! I discovered your addons in B2B site, and they are awesome. Thanks for the works.

I want to share them on my TBC 2.4.3 discord addons : https://discord.gg/5qVu56M

I just want some info about those addons, and if possible a screen, but just some infos and how to use them can be great. :)

Arphint
Followme
Lootbets
All the Spikes addon (i know Charlink, but it wasn't working for me : /, is it the same than SpikesCharlink? Or updated?)
ULGC
UnitRoles
RaidStats

Is it the same version on the B2B site and here? Or you updated them?

Also did you updated/fixed something on other addons? (Weak Aura, Xperl, DBM.....)

Thanks in advance.

**Comment by Spikeone** [comment]
Hey @Macumbafeh,

trying to answer anything I can.

Arphint: 
An addon I wrote for a player which shows the armor (and attack speed of mainhand / offhand) of the target in a small frame.
This addon was superseded by a weakaura I wrote.

Followme:
An addon I wrote which provides a simple command: All chars that have the addon enabled will follow the player who writes in group/raid chat "fme". We have (up to) 5 accounts for each player, so this was a simple helper for playing multiple chars (not fond with any multiboxing tools).

Lootbets:
Just an idea, nothing more (one could bet what items a boss drops, possibly betting gold or something alike).

SpikesAuraWatch:
Addon which reminds me to enable shadow form, righteous fury, moonkin form, that other druid spell - forgot those quite often. Can be superseded by weakauras.

SpikesCharLink:
Should work on any TBC Client, you may need to explain what "doesnt work". This requires the server to allow "fake" item links. Otherwise this addon would need an enhancement to create it's own links (like chatter does).

SpikesDordonHelper:
This is a helper for our raidtracker. Loot is only shown in a 100m distance and not tracked otherwise (e.g. 2nd boss in mount hyjal and everbody rides off)

SpikesEasyMarks:
An addon which automatically sets raidicons over specific guids (requires the server to have fixed guids).

SpikesProfressionLink:
Unfinished addon which would allow linking professions just as in WOTLK. Also requires the server to allow "fake" item links.

SpikesTargetAnnouncer:
Unfinished addon which allows setting CC icons for specific players and posting them. That way one doesn't have to remember who had which target.

ULGC:
Unfinished addon which allows a "gearcheck". We have a level 60 guild and TBC items are not allowed (by choice). So I wrote that one.

UnitRoles:
Helper Addon for finding out what role a player has. That way one could automate certain addons (e.g. PallyPower).

RaidStats:
Also unfinished, should display some raidstats e.g. who casted most fireballs - or whatever.

I only uploaded addons I altered in some way for some reasons. Some of them might only work with german clients (sadly) as I don't own an english client.

**Comment by Macumbafeh** [comment]
Thanks a lot for the fast reply ! i'll test them.

I couldn't make to work SimpleRaidSwap with 2 accounts. idk why, even if i added /srs auth 'player' ect

For Charlink i guess serv doesn't allow fake item. because there were nothing in chat
edit : i think it's a serv side, i tried on endless and i have nothing but it doesn't work.
On Netherwing i have that : 
![image](https://user-images.githubusercontent.com/47739411/111000004-8c222580-8381-11eb-9042-e278a1539b19.png)

**Comment by Spikeone** [comment]
> I couldn't make to work SimpleRaidSwap with 2 accounts. idk why, even if i added /srs auth 'player' ect

There sometimes is a bug which requires you to login and out at least once after enabling - don't ask me why

> On Netherwing i have that :

Yeah, looking like sending fake links, in that case more specific colored text, is not allowed (the charlinks are class colored). Sadly I wont update the addon to send it's own format (which shouldn't be hard but well, what for should I do that?).

**Comment by Macumbafeh** [comment]
Thanks a lot
